name: Java CI

on:
  push:
    branches:
      - master
      - release/*

  pull_request:
    branches:
      - master
      - release/*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: check release tag
      run: scripts/check-release.sh

    - name: Build with Maven
      if: github.event_name == 'pull_request'
      run: mvn -B package

    - name: deploy maven artifact
      if: github.event_name == 'push'
      run: scripts/deploy.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor }}

    - name: tag release
      if: github.event_name == 'push'
      run: scripts/tag-release.sh

    - name: set maven artifact properties
      id: maven_artifact_properties
      if: github.event_name == 'push'
      run: scripts/maven-artifact.sh

    - name: create release
      id: create_release
      if: github.event_name == 'push'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.maven_artifact_properties.outputs.maven_artifact_version }}
        release_name: ${{ steps.maven_artifact_properties.outputs.maven_artifact_version }}
        draft: false
        prerelease: true

    - name: upload release asset
      id: upload-release-asset
      if: github.event_name == 'push'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/${{ steps.maven_artifact_properties.outputs.maven_artifact }}
        asset_name: ${{ steps.maven_artifact_properties.outputs.maven_artifact }}
        asset_content_type: application/zip
