name: Java CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: check release tag
      if: github.event_name == 'pull_request'
      run: scripts/check-release.sh
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: tag release
      if: github.event_name == 'push'
      run: scripts/tag-release.sh
